const mongoose = require('mongoose');

const proposalSchema = new mongoose.Schema({
  proposalNumber: { type: String, unique: true },
  title: { type: String, required: true, trim: true },
  proposalType: { type: String, default: 'standard' },
  client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', default: null },
  contactPersons: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Contact' }],
  deal: { type: mongoose.Schema.Types.ObjectId, ref: 'Deal', default: null },
  proposalOwner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  lastModifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  proposalDate: Date,
  validUntil: Date,
  submissionDate: Date,
  issueDate: Date,
  expiryDate: Date,
  status: { type: String, enum: ['draft', 'pending-approval', 'approved', 'sent', 'revised', 'accepted', 'rejected', 'expired', 'withdrawn'], default: 'draft' },
  internalApprovalRequired: { type: Boolean, default: false },
  clientRequirements: { type: String, default: '' },
  scopeOfWork: { type: String, default: '' },
  solutionOverview: { type: String, default: '' },
  deliverables: { type: Array, default: [] },
  exclusions: { type: String, default: '' },
  assumptions: { type: String, default: '' },
  dependencies: { type: String, default: '' },
  paymentTerms: { type: String, default: '' },
  executionTimeline: { type: String, default: '' },
  warrantyTerms: { type: String, default: '' },
  supportTerms: { type: String, default: '' },
  slaReference: { type: String, default: '' },
  confidentialityClause: { type: String, default: '' },
  terminationClause: { type: String, default: '' },
  governingLaw: { type: String, default: '' },
  estimatedValue: { type: Number, default: 0 },
  currency: { type: String, default: 'INR' },
  language: { type: String, default: 'English' },
  industry: { type: String, default: '' },
  tags: { type: [String], default: [] },
  notes: { type: String, default: '' },
  items: { type: Array, default: [] },
  subtotal: { type: Number, default: 0 },
  taxRate: { type: Number, default: 0 },
  tax: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  total: { type: Number, default: 0 },
  terms: { type: String, default: '' },
  pdfUrl: { type: String, default: '' },
  emailSent: { type: Boolean, default: false },
  emailSentAt: Date,
  acceptedDate: Date,
  convertedToQuotation: { type: mongoose.Schema.Types.ObjectId, ref: 'Quotation', default: null },
  convertedToInvoice: { type: mongoose.Schema.Types.ObjectId, ref: 'Invoice', default: null },
  isDeleted: { type: Boolean, default: false }
}, { timestamps: true });

module.exports = mongoose.model('Proposal', proposalSchema);
