const Goal = require('../models/Goal');
const PerformanceReview = require('../models/PerformanceReview');
const Employee = require('../models/Employee');

const result = (res, data) => res.json({ success: true, data });
exports.getGoals = async (req, res) => { try { const employee = req.params.employeeId || (await Employee.findOne({ user: req.user._id }))?._id; result(res, await Goal.find(employee ? { assignedTo: employee } : {}).populate('assignedTo', 'employeeId designation').sort({ targetDate: 1 })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.getGoal = async (req, res) => { try { result(res, await Goal.findById(req.params.id)); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.getAllGoals = async (req, res) => { try { result(res, await Goal.find().sort({ targetDate: 1 })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.createGoal = async (req, res) => { try { res.status(201).json({ success: true, data: await Goal.create({ ...req.body, assignedBy: req.user._id }) }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
exports.updateGoal = async (req, res) => { try { result(res, await Goal.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true })); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
exports.createReview = async (req, res) => { try { res.status(201).json({ success: true, data: await PerformanceReview.create({ ...req.body, reviewer: req.user._id }) }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
exports.updateReview = async (req, res) => { try { result(res, await PerformanceReview.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true })); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
exports.getReviews = async (req, res) => { try { const employee = req.query.employeeId ? req.query.employeeId : (await Employee.findOne({ user: req.user._id }))?._id; result(res, await PerformanceReview.find(employee ? { employee } : {}).populate('employee', 'employeeId designation').sort({ createdAt: -1 })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.getAllReviews = async (req, res) => { try { result(res, await PerformanceReview.find().populate('employee', 'employeeId designation').sort({ createdAt: -1 })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.submitSelfReview = async (req, res) => { try { result(res, await PerformanceReview.findByIdAndUpdate(req.params.id, { selfAssessment: req.body.selfReview || req.body, status: 'self_submitted' }, { new: true })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.submitManagerReview = async (req, res) => { try { result(res, await PerformanceReview.findByIdAndUpdate(req.params.id, { managerAssessment: req.body.managerReview || req.body, status: 'completed', reviewer: req.user._id }, { new: true })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.submitSelfAssessment = exports.submitSelfReview;
exports.submitManagerAssessment = exports.submitManagerReview;
exports.getEmployeeReviews = async (req, res) => { try { result(res, await PerformanceReview.find({ employee: req.params.employeeId }).sort({ createdAt: -1 })); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
exports.createCycle = async (req, res) => result(res, { ...req.body, createdBy: req.user._id });
exports.getCycles = async (req, res) => result(res, []);